### ISSUE TITLE
[Wishlist] Make "sha256sum" file be extended by the iso2zip.sh

### ISSUE THREAD

**Issue by chinyakao** [hugh712/hugh_script#1]
In the end of `tools/iso2zip.sh`, will have a "sha256sum" file for the zip file. May we extend the "sha256sum" file if the directory already has the "sha256sum" file for iso?

**Comment by hugh712** [comment]
will just have an update as:

```
diff --git a/tools/iso2zip.sh b/tools/iso2zip.sh
index 46a2fff..5506b09 100755
--- a/tools/iso2zip.sh
+++ b/tools/iso2zip.sh
@@ -15,7 +15,7 @@ fi

 folder=${IMG%"$suffix"};
 zipfile="$folder".zip
-checksumfile="$folder".sha256sum
+checksumfile="$zipfile".sha256sum

 rm -rf "$folder"
```
so the file name should be  yourimage.zip.sha256sum

**Comment by hugh712** [comment]
this issue has been fixed in 
https://github.com/hugh712/hugh_script/commit/b635eedd10a827f3fda1aada5aa793d0a35adf68
