### ISSUE TITLE
[Debug] suggest not using "[]" in grep command

### ISSUE THREAD

**Issue by chinyakao** [hugh712/hugh_script#2]
https://github.com/hugh712/hugh_script/blob/fa6af0e312beef5adf22ee7eb253dc4ee43afcb7/log/gfx/i915_collect.sh#L50

It can grep the log by `dmesg | grep 'drm:intel_dp_get_dsc_sink_cap`.
But cannot grep the log by `dmesg | grep 'drm:intel_dp_get_dsc_sink_cap [i915]]'`

**Comment by hugh712** [comment]
fixed in https://github.com/hugh712/hugh_script/commit/d725b10fc9fcf2d2a3719738bfc4ea3ba6cb15a9
